### PR TITLE
Upgrade to Cake4.

### PR DESCRIPTION
**Pull request by dereuromark**
Prepare for beta release

### CODE REVIEW

**Comment by Ali1** [comment]
yep works thank you!

**Comment by Ali1** [comment]
I'm getting a memory leak with this. Looking into it.

**Comment by Ali1** [comment]
Sorry I didn't reply. FYI ignore my last msg.

**Comment by dereuromark** [comment]
I tagged an RC, please QA this one, if all good we can release stable.

**Comment by Ali1** [comment]
I've been using it on production server for 1+ months now without issue.

**Pull request merged**
